import Head from 'next/head';
import Navbar from '../components/Navbar/index';
import Banner from '../components/Banner/index';
import Companies from '../components/Companies/index';
import Work from '../components/Work/index';
import Table from '../components/Table/index';
import Features from '../components/Features/index';
import Simple from '../components/Simple/index';
import Trade from '../components/Trade/index';
import Faq from '../components/Faq/index';
import Footer from '../components/Footer/index';

export default function Home() {
  return (
    <>
      <Head>
        <title>CrCrypto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/Logo/logo.svg" />
      </Head>
      <main>
        <Navbar />
        <Banner />
        <Companies />
        <Work />
        <Table />
        <Features />
        <Simple />
        <Trade />
        <Faq />
        <Footer />
      </main>
    </>
  )
}
